### PR TITLE
Rename long-polling to regular polling in HTMX tutorial

### PR DESCRIPTION
**Pull request by FantasyTeddy**
As mentioned in #13, the term "long-polling" usually refers to something slightly different, than is shown in the tutorial.

Since this is much more of a "regular polling" approach, I would suggest this rename to prevent confusion.

### CODE REVIEW

**Comment by pauleveritt** [comment]
@khalidabuhakmeh Any opinions on this?

**Comment by khalidabuhakmeh** [comment]
I think it's good, we just need a redirect URL

**Comment by FantasyTeddy** [comment]
Is the redirect URL something I should add in this PR?
If so, could you give me some hints how to do it?

**Review by khalidabuhakmeh — APPROVED** [review]
I've updated with the `obsoletes` front matter. Thanks for the changes.

**Pull request merged**
